### ISSUE TITLE
(iOS )Tap not worked after refresh nativeView.refresh

### ISSUE THREAD

**Issue by Viking0607** [manijak/nativescript-carousel#123]
Carousel updated to 6.1.0.
I use Carousel and after changed data in Carousel with watch tap event doesn't work.

``` 
watch: {
    firstPlaceList() {
      this.$nextTick(() => {
        this.$refs.carouselFirst.nativeView.refresh();
      });
    }
}
```

Get data
```
this.$http
.request({
    url: SERVER_PATH + "",
    method: "POST",
    headers: { "Content-Type": "application/json" },
    content: JSON.stringify({
    token: this.$store.getters.getUserToken,
    method: "users.getRating",
    data: {}
    })
})
.then(
    response => {
    const responseStatusCode = response.statusCode;
    const result = response.content.toJSON();
    const hasError = result.error;

    if (!hasError) {
        const resultData = JSON.parse(result.data);
        this.firstPlaceList = resultData.first || [];
        this.secondPlaceList = resultData.second || [];
        this.thirdPlaceList = resultData.third || [];
        this.itemList = resultData.tail || [];
    } else {
        const errorName = result.errorName;
        showToasty(getTextErrorByErrorName(errorName), "danger");
        this.checkAuthError(errorName);
    }
    },
    e => {
    showToasty(
        "Во время выполнения запроса произошла ошибка!",
        "danger"
    );
    }
)
```
And the carousel itself
```
<Carousel
    ref="carouselFirst"
    ios:indicatorOffset="0,-10"
    ios:finite="true"
    ios:bounce="false"
    showIndicator="false"
    indicatorAnimation="SWAP"
    indicatorColor="#66ccff"
    indicatorColorUnselected="#cceeff"
    height="100%"
    width="100%"
>
    <CarouselItem
    v-for="(item, key) in firstPlaceList"
    @tap="onItemTap({userId:item.userId})"
    :key="key"
    >
    <StackLayout>
        <Image
        class="img--medium circle m-l-10"
        :src="SERVER_PATH_IMAGE+item.image"
        loadMode="async"
        stretch="aspectFill"
        />
    </StackLayout>
    </CarouselItem>
</Carousel>
```

And **onItemTap** doesn't work after refresh data

**Comment by spasma** [comment]
@Viking0607 What a disaster.. I had the same issue since a few days. I searched for hours to fix this with an angry client looking over my shoulder.. reverted to old branches where it was working, reinstalled everything, updated nativescript, all without success..

After hours of this investigation, I found a "fix" for this issue. the Cocao Pod for DKCarouselView was updated with an erroneous version. 

You can fix this issue by manually changing the Podfile in /platforms/ios/.
Change it from:

`pod 'DKCarouselView'`

 to

`pod 'DKCarouselView', :git => 'https://github.com/manijak/DKCarouselView', :commit => '57a75a8144ccb99b506742ed364e4e5534606563'`

Hopefully this will fix your issue as well!

**Comment by manijak** [comment]
Welcome to the world of open source, where user contribution is very much welcome. 👍 

@spasma don't know what version of the plugin you were running but the Pod file does not contain only `pod 'DKCarouselView'`, that sounds very old. If you look at the source you'll see that the full path in the pod file is: 
`pod 'DKCarouselView', :git => 'https://github.com/manijak/DKCarouselView'`

Also the "fix" you provided, to rollback the pod to a version from 2017, seems kinda off. especially since the nativescript-plugin itself is based on the latest commit. That might give you issues in other places, but if it works for you...

To me this seems like a Vue-only issue. Now, I'm no vue-developer and I don't use it. I have truly done my best to provide a somewhat working version to the users with examples, but my knowledge and time is limited. Therefore this is something where the nativescript-vue community needs to step in and provide a more complete solution.

**Comment by spasma** [comment]
@manijak I'm on the latest nativescript 5 release and the latest nativescript-carousel on the 4 release, the podfile is automaticly generated from that. You're responding like I'm directly putting you down. I was angry at the situation, not at you.. 

You're right, the pod description you mentioned is the one in the podfile, but it breaks the (tap) on the CarouselItem in my Angular environment. On iOS only. That's why I thought it's related.. 

Maybe this is another bug.. You're also right that it's a 2017 version, but there are only 4 commits after that and they're all from the last month.. Since that time it's broken, so that's quite a coincidence. 

Nevertheless, you won't see me complaining here anymore, it's working for me. I was just trying to help someone out here ✌️

**Comment by manijak** [comment]
It's an odd one... I did not manage to reproduce it in ns6 with version 6.x of the plugin. I did come accross a different issue tho, that made views dissapear when adding new items & calling refresh. You can try the demo apps included in the repo and test for yourself. 

The fixes are now available on a separate branch:
`pod 'DKCarouselView', :git => 'https://github.com/manijak/DKCarouselView', :branch => 'dev'`

**Comment by spasma** [comment]
@manijak The dev-branch seems to work w/ ns5 angular. Thank you very much!

**Comment by manijak** [comment]
Great! Thanks for the feedback. I'll see to it and merge it to master.
