### ISSUE TITLE
[iOS] Auto adjusting width upon device rotation

### ISSUE THREAD

**Issue by ryanzaatari** [manijak/nativescript-carousel#25]
How to handle device rotation to adjust width, as currently the images preserve their initially loaded dimensions.
I'm setting CarouselItem width="100%" and the image element's width to 100% as well.
Am I missing anything ?

**Comment by manijak** [comment]
No, you are not missing anything. There seems to be an issue with orientation-change on iOS. It sets the Carousel width to be the initial page-width. 

On Android is should work out of the box...

**Comment by ryanzaatari** [comment]
@manijak is there any way to go about this, as I'll have to lock rotation otherwise, or check other alternatives.

**Comment by manijak** [comment]
As of now, there is not. The issue could be deeper inside the iOS Pod we are using. So I'll have to take some time and dig inn. 

Your best bet would be to disable rotation on the view that is using the Carousel, or just find something else in the meantime.

**Comment by manijak** [comment]
Ok, looks like I've found a solution. Will be available in the next release. So you will be forced to move over to TNS 3.x if you want the fix.

**Comment by ryanzaatari** [comment]
I see, will be waiting for the next release then.

**Comment by manijak** [comment]
Just released v3 (that only supports tns 3). Orientation fix applied BUT, in order to trigger the `refresh` on orientation change, you need the `nativescript-orientation` plugin. 
https://www.npmjs.com/package/nativescript-orientation

All you need to do is install it, and just attach to the orientation-change event. Nothing more. This will trigger the ui refresh on all child views.
